import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "./components/shared/Navbar";

const roboto_init = Roboto(
  { subsets: ["latin"],
    weight:['100','300','700'],
    variable: "--font-roboto",
   });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto_init.variable}>
      <Navbar/>
        {children}
        </body>
    </html>
  );
}
